### ISSUE TITLE
elevation_mapping received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by Rayman** [ethz-asl/elevation_mapping#62]
Hey,

Can someone help me solve this crashing issue? It happens quite frequently while mapping. I've got a backtrace below. I'm running the master version of the code.

```
(gdb) bt
#0  0x00007ffff67dfe68 in grid_map::GridMap::at(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Eigen::Array<int, 2, 1, 0, 2, 1> const&) const ()
   from /opt/ros/kinetic/lib/libgrid_map_core.so
#1  0x00007ffff67dffce in grid_map::GridMap::isValid(Eigen::Array<int, 2, 1, 0, 2, 1> const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const () from /opt/ros/kinetic/lib/libgrid_map_core.so
#2  0x00007ffff7ba007f in elevation_mapping::ElevationMap::fuse (this=this@entry=0x7fffffffc270, topLeftIndex=..., size=...) at /home/rayman/catkin_ws/src/elevation_mapping/src/ElevationMap.cpp:307
#3  0x00007ffff7ba1d32 in elevation_mapping::ElevationMap::fuseAll (this=this@entry=0x7fffffffc270) at /home/rayman/catkin_ws/src/elevation_mapping/src/ElevationMap.cpp:193
#4  0x00007ffff7b780f2 in elevation_mapping::ElevationMapping::publishFusedMapCallback (this=0x7fffffffb810) at /home/rayman/catkin_ws/src/elevation_mapping/src/ElevationMapping.cpp:335
#5  0x00007ffff786014b in ros::TimerManager<ros::Time, ros::Duration, ros::TimerEvent>::TimerQueueCallback::call() () from /opt/ros/kinetic/lib/libroscpp.so
#6  0x00007ffff78866f8 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/kinetic/lib/libroscpp.so
#7  0x00007ffff78880fb in ros::CallbackQueue::callAvailable(ros::WallDuration) () from /opt/ros/kinetic/lib/libroscpp.so
#8  0x00007ffff7b7613a in elevation_mapping::ElevationMapping::runFusionServiceThread (this=0x7fffffffb810) at /home/rayman/catkin_ws/src/elevation_mapping/src/ElevationMapping.cpp:224
#9  0x00007ffff3abb5d5 in ?? () from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0
#10 0x00007ffff38946ba in start_thread (arg=0x7fffddffb700) at pthread_create.c:333
#11 0x00007ffff6d3d41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by reinzor** [comment]
```
elevation_mapping: /usr/include/eigen3/Eigen/src/Eigenvalues/EigenSolver.h:347: Eigen::EigenSolver<_MatrixType>::EigenvectorsType Eigen::EigenSolver<_MatrixType>::eigenvectors() const [with _MatrixType = Eigen::Matrix<double, 2, 2>; Eigen::EigenSolver<_MatrixType>::EigenvectorsType = Eigen::Matrix<std::complex<double>, 2, 2>; typename Eigen::NumTraits<typename Derived::Scalar>::Real = double]: Assertion `m_eigenvectorsOk && "The eigenvectors have not been computed together with the eigenvalues."' failed.
```
